# Generated by Django 4.1 on 2022-10-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variationcategory_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationcategory',
            options={'verbose_name': 'variation category', 'verbose_name_plural': 'variation Categories'},
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='variation',
            new_name='variation_category',
        ),
    ]
