# Generated by Django 4.1 on 2022-11-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product Gallery'},
        ),
    ]
