# Generated by Django 4.1 on 2022-11-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_users_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='users',
            new_name='user',
        ),
    ]
