# Generated by Django 4.1 on 2022-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderproduct_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
